name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Sync to Hugging Face Hub
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          huggingface_repo_id: mohitbakre/churn-prediction-api
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
          private: false # Explicitly set to a boolean value