name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Hub
        uses: huggingface/actions/docker-push@v3.4.0
        with:
          # Your Hugging Face Space repository name
          space: your-huggingface-username/churn-prediction-api
          # Your Hugging Face token secret
          token: ${{ secrets.HF_TOKEN }}