name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Hugging Face
        uses: docker/login-action@v3
        with:
          registry: registry.huggingface.co
          username: ${{ github.actor }}
          password: ${{ secrets.HF_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.huggingface.co/${{ github.repository }}:latest