name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Hugging Face
        uses: docker/login-action@v2
        with:
          # Use the Hugging Face registry URL
          registry: registry.hf.co
          # Use your Hugging Face username for authentication
          username: ${{ github.actor }}
          # Use the Hugging Face token secret
          password: ${{ secrets.HF_TOKEN }}

      - name: Build and push Docker image
        env:
          # Your Docker image name (can be anything)
          IMAGE_NAME: churn-prediction-api
          # The name of your Hugging Face Space
          HF_SPACE_NAME: mohitbakre/churn-prediction-api
        run: |
          # Build the Docker image
          docker build -t $IMAGE_NAME .
          # Tag the image with the Hugging Face registry URL
          docker tag $IMAGE_NAME:latest registry.hf.co/$HF_SPACE_NAME:latest
          # Push the image to the Hugging Face registry
          docker push registry.hf.co/$HF_SPACE_NAME:latest