name: MLOps Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest  # Use a standard Linux runner in the cloud

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true # This is crucial! It tells GitHub Actions to download LFS files.

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify the Python version you used locally

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clean MLflow cache and artifacts
      run: |
        rm -rf .mlflow mlruns

    - name: Clear MLflow env vars (avoid Windows path issues)
      run: |
          unset MLFLOW_TRACKING_URI
          unset MLFLOW_ARTIFACT_URI

    - name: Run MLflow training script
      run: |
        python src/train.py

    # This step will upload the MLflow artifacts to a central location.
    # For a simple, free setup, we will use a local directory on the runner itself.
    # In a production scenario, you would configure MLflow to use a remote backend store.
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/